apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant-fastmcp-api
  labels:
    app: qdrant-fastmcp-api
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qdrant-fastmcp-api
  template:
    metadata:
      labels:
        app: qdrant-fastmcp-api
        version: v1
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
      - name: fastmcp-api
        image: qdrant-fastmcp-api:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: QDRANT_URL
          valueFrom:
            configMapKeyRef:
              name: qdrant-fastmcp-config
              key: qdrant-url
        - name: QDRANT_API_KEY
          valueFrom:
            secretKeyRef:
              name: qdrant-fastmcp-secrets
              key: qdrant-api-key
        - name: EMBEDDING_MODEL
          valueFrom:
            configMapKeyRef:
              name: qdrant-fastmcp-config
              key: embedding-model
        - name: MAX_CONNECTIONS
          value: "100"
        - name: CONNECTION_POOL_SIZE
          value: "20"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          capabilities:
            drop:
            - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-fastmcp-api
  labels:
    app: qdrant-fastmcp-api
spec:
  selector:
    app: qdrant-fastmcp-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qdrant-fastmcp-config
data:
  qdrant-url: "http://qdrant-service.qdrant.svc.cluster.local:6333"
  embedding-model: "nomic-ai/CodeRankEmbed"
  supported-collections: "sentence_transformers_768,docling_768,qdrant_ecosystem_768"

---
apiVersion: v1
kind: Secret
metadata:
  name: qdrant-fastmcp-secrets
type: Opaque
data:
  # Base64 encoded API key
  qdrant-api-key: <base64-encoded-key>

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: qdrant-fastmcp-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qdrant-fastmcp-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qdrant-fastmcp-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.qdrant-fastmcp.example.com
    secretName: qdrant-fastmcp-tls
  rules:
  - host: api.qdrant-fastmcp.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qdrant-fastmcp-api
            port:
              number: 8080

---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: qdrant-fastmcp-api-monitor
  labels:
    app: qdrant-fastmcp-api
spec:
  selector:
    matchLabels:
      app: qdrant-fastmcp-api
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s