version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    networks:
      - qdrant-network

  qdrant-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    container_name: qdrant-mcp-server
    depends_on:
      - qdrant
    volumes:
      - ./mcp_server:/app/mcp_server
      - ./src:/app/src
      - ./output:/app/output
    environment:
      - QDRANT_URL=http://qdrant:6333
      - EMBEDDING_MODEL=nomic-ai/CodeRankEmbed
      - COLLECTIONS=docling,viator_api,fast_docs,pydantic_docs,inngest_ecosystem
    restart: unless-stopped
    networks:
      - qdrant-network
    stdin_open: true
    tty: true
    command: python mcp_server/qdrant_fastmcp_server.py

volumes:
  qdrant_storage:

networks:
  qdrant-network:
    driver: bridge
